# -*- coding: utf-8 -*-
"""California House Price.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vUc8H85CysU8V9pDzBPn3AKYlKl5yR_H
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

dfC = pd.read_excel("California House Price.xlsx")

df = dfC.copy()

df.head(3)

df.tail(3)

df.shape

df.info()

df.describe().T

df.isnull().sum()

df.dropna(subset=['total_bedrooms'], inplace=True)

df.isnull().sum()

plt.figure(figsize=(17,6))
sns.lineplot(x= "ocean_proximity", y= "median_house_value", data = df, color = "red", ci = None)
plt.title("House Price by Ocean Proximity")
plt.xlabel("Ocean Proximity")
plt.ylabel("Median House Value")
plt.xticks(rotation = 50)
plt.tight_layout()
plt.show()

correlation = df.select_dtypes(include=[float, int])

corr = correlation.corr()

print(corr)

plt.figure(figsize=(17,6))
sns.heatmap(corr, annot=True, cmap="Set3", fmt=".2f", linewidths=0.5, linecolor="red")
plt.tight_layout()
plt.show()

plt.figure(figsize=(17,6))
sns.pairplot(df, hue = "median_house_value", diag_kind='kde')
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))
plt.scatter(df['longitude'], df['latitude'], c=df['median_house_value'], cmap='viridis', marker='o', edgecolor='k', alpha=0.5)
plt.colorbar(label='Median House Value')
plt.xlabel('Longitude')
plt.ylabel('Latitude')
plt.title('Geographical Distribution of House Values')
plt.show()

plt.figure(figsize=(8, 6))
sns.boxplot(x='ocean_proximity', y='median_house_value', data=df, color = "red")
plt.title('House Value by Ocean Proximity')
plt.show()